export interface Question {
  id: number;
  text: string;
  category: string;
}

export const MI_QUESTIONS: Question[] = [
  // Word Smart
  { id: 1, text: "I can teach people very well.", category: "Word Smart" },
  { id: 2, text: "I enjoy writing letters or emails.", category: "Word Smart" },
  { id: 3, text: "I like to read for pleasure.", category: "Word Smart" },
  { id: 4, text: "I am good at finding my way with words.", category: "Word Smart" },
  { id: 5, text: "I enjoy playing word games like Scrabble or Crosswords.", category: "Word Smart" },
  // Logic Smart
  { id: 6, text: "I enjoy solving math problems.", category: "Logic Smart" },
  { id: 7, text: "I like to figure out how things work.", category: "Logic Smart" },
  { id: 8, text: "I am good at strategy and logic games.", category: "Logic Smart" },
  { id: 9, text: "I like to make sense of things by organizing them.", category: "Logic Smart" },
  { id: 10, text: "I prefer step-by-step instructions.", category: "Logic Smart" },
  // Picture Smart
  { id: 11, text: "I am good at drawing or sketching.", category: "Picture Smart" },
  { id: 12, text: "I enjoy photography or visual arts.", category: "Picture Smart" },
  { id: 13, text: "I have a good sense of direction.", category: "Picture Smart" },
  { id: 14, text: "I like to use maps and charts.", category: "Picture Smart" },
  { id: 15, text: "I can visualize things clearly in my head.", category: "Picture Smart" },
  // Body Smart
  { id: 16, text: "I am good at sports or physical activities.", category: "Body Smart" },
  { id: 17, text: "I like to build things with my hands.", category: "Body Smart" },
  { id: 18, text: "I cannot sit still for long periods of time.", category: "Body Smart" },
  { id: 19, text: "I enjoy outdoor activities and exercise.", category: "Body Smart" },
  { id: 20, text: "I have good physical coordination.", category: "Body Smart" },
  // Music Smart
  { id: 21, text: "I can play a musical instrument.", category: "Music Smart" },
  { id: 22, text: "I can sing in tune.", category: "Music Smart" },
  { id: 23, text: "I often have a song stuck in my head.", category: "Music Smart" },
  { id: 24, text: "I am sensitive to sounds in my environment.", category: "Music Smart" },
  { id: 25, text: "I enjoy listening to music frequently.", category: "Music Smart" },
  // People Smart
  { id: 26, text: "I am good at working in a team.", category: "People Smart" },
  { id: 27, text: "I am a good listener.", category: "People Smart" },
  { id: 28, text: "I enjoy meeting new people.", category: "People Smart" },
  { id: 29, text: "I am sensitive to other's moods and feelings.", category: "People Smart" },
  { id: 30, text: "I enjoy social gatherings and networking.", category: "People Smart" },
  // Self Smart
  { id: 31, text: "I know my own strengths and weaknesses.", category: "Self Smart" },
  { id: 32, text: "I prefer working alone.", category: "Self Smart" },
  { id: 33, text: "I set goals for myself.", category: "Self Smart" },
  { id: 34, text: "I like to reflect on my thoughts and feelings.", category: "Self Smart" },
  { id: 35, text: "I am a self-motivated person.", category: "Self Smart" },
  // Nature Smart
  { id: 36, text: "I enjoy gardening or being around plants.", category: "Nature Smart" },
  { id: 37, text: "I like to be in nature and outdoors.", category: "Nature Smart" },
  { id: 38, text: "I am sensitive to the environment and weather.", category: "Nature Smart" },
  { id: 39, text: "I enjoy learning about animals and wildlife.", category: "Nature Smart" },
  { id: 40, text: "I care about environmental issues.", category: "Nature Smart" },
];

export const INTEREST_QUESTIONS: Question[] = [
  // Engineering/Technology
  { id: 41, text: "Designing and building robots.", category: "Technical" },
  { id: 42, text: "Developing software applications.", category: "Technical" },
  { id: 43, text: "Understanding how electrical circuits work.", category: "Technical" },
  { id: 44, text: "Managing large-scale construction projects.", category: "Technical" },
  { id: 45, text: "Innovating renewable energy solutions.", category: "Technical" },
  { id: 46, text: "Fixing complex mechanical systems.", category: "Technical" },
  { id: 47, text: "Working with aerospace technology.", category: "Technical" },
  { id: 48, text: "Designing automotive engines.", category: "Technical" },
  { id: 49, text: "Maintaining computer hardware systems.", category: "Technical" },
  { id: 50, text: "Studying chemical properties for industry.", category: "Technical" },
  // Health & Life Sciences
  { id: 51, text: "Treating patients in a clinical setting.", category: "Medical" },
  { id: 52, text: "Performing medical research in a lab.", category: "Medical" },
  { id: 53, text: "Studying human anatomy and biology.", category: "Medical" },
  { id: 54, text: "Developing new pharmaceutical drugs.", category: "Medical" },
  { id: 55, text: "Specializing in surgical procedures.", category: "Medical" },
  { id: 56, text: "Caring for animals as a veterinarian.", category: "Medical" },
  { id: 57, text: "Working on public health awareness.", category: "Medical" },
  { id: 58, text: "Analyzing dental health and hygiene.", category: "Medical" },
  { id: 59, text: "Applying physiotherapy for recovery.", category: "Medical" },
  { id: 60, text: "Studying genetic engineering.", category: "Medical" },
  // Finance & Accounting
  { id: 61, text: "Managing investment portfolios.", category: "Finance" },
  { id: 62, text: "Auditing corporate financial records.", category: "Finance" },
  { id: 63, text: "Analyzing stock market trends.", category: "Finance" },
  { id: 64, text: "Calculating tax returns and liabilities.", category: "Finance" },
  { id: 65, text: "Working in banking or loan processing.", category: "Finance" },
  { id: 66, text: "Strategic financial planning for firms.", category: "Finance" },
  { id: 67, text: "Evaluating risk in insurance sectors.", category: "Finance" },
  { id: 68, text: "Managing a company's budget.", category: "Finance" },
  { id: 69, text: "Forecasting economic shifts.", category: "Finance" },
  { id: 70, text: "Retail banking and customer accounts.", category: "Finance" },
  // Business & Management
  { id: 71, text: "Leading a startup or new business.", category: "Business" },
  { id: 72, text: "Managing human resources and staff.", category: "Business" },
  { id: 73, text: "Overseeing marketing and branding.", category: "Business" },
  { id: 74, text: "Strategic planning for organizations.", category: "Business" },
  { id: 75, text: "Handling public relations for clients.", category: "Business" },
  { id: 76, text: "Managing supply chain and logistics.", category: "Business" },
  { id: 77, text: "International trade and business deal.", category: "Business" },
  { id: 78, text: "Store management and retail operations.", category: "Business" },
  { id: 79, text: "Event planning and corporate hosting.", category: "Business" },
  { id: 80, text: "Consulting firms on efficiency.", category: "Business" },
  // Humanities & Law
  { id: 81, text: "Practicing law in a court of justice.", category: "Humanities" },
  { id: 82, text: "Studying historical events and culture.", category: "Humanities" },
  { id: 83, text: "Reporting news and social journalism.", category: "Humanities" },
  { id: 84, text: "Working in social work and charity.", category: "Humanities" },
  { id: 85, text: "Psychology and mental health therapy.", category: "Humanities" },
  { id: 86, text: "Politcal science and public policy.", category: "Humanities" },
  { id: 87, text: "Philosophy and ethics research.", category: "Humanities" },
  { id: 88, text: "Archaeology and heritage preservation.", category: "Humanities" },
  { id: 89, text: "Linguistics and studying languages.", category: "Humanities" },
  { id: 90, text: "Criminology and criminal forensics.", category: "Humanities" },
  // Fine Arts & Design
  { id: 91, text: "Painting, sketching and visual arts.", category: "Arts" },
  { id: 92, text: "Graphic design and digital illustration.", category: "Arts" },
  { id: 93, text: "Interior styling and architecture.", category: "Arts" },
  { id: 94, text: "Fashion design and garment creation.", category: "Arts" },
  { id: 95, text: "Photography and visual capture.", category: "Arts" },
  { id: 96, text: "Sculpting and 3D physical modeling.", category: "Arts" },
  { id: 97, text: "Animation and video game art.", category: "Arts" },
  { id: 98, text: "Textile and fabric design.", category: "Arts" },
  { id: 99, text: "Jewellery and accessory design.", category: "Arts" },
  { id: 100, text: "Product and industrial design.", category: "Arts" },
  // Performing Arts
  { id: 101, text: "Acting in theatre or cinema.", category: "Performing" },
  { id: 102, text: "Classical or modern dance.", category: "Performing" },
  { id: 103, text: "Composing or performing music.", category: "Performing" },
  { id: 104, text: "Singing professionally.", category: "Performing" },
  { id: 105, text: "Directing films or documentaries.", category: "Performing" },
  { id: 106, text: "Playing musical instruments.", category: "Performing" },
  { id: 107, text: "Scriptwriting and storytelling.", category: "Performing" },
  { id: 108, text: "Choreography for dance shows.", category: "Performing" },
  { id: 109, text: "Voice-over and radio modulation.", category: "Performing" },
  { id: 110, text: "Sound engineering for media.", category: "Performing" },
  // Security & Defences
  { id: 111, text: "Serving in the military or army.", category: "Security" },
  { id: 112, text: "Police and law enforcement works.", category: "Security" },
  { id: 113, text: "Aviation and pilot operations.", category: "Security" },
  { id: 114, text: "Navy and maritime security.", category: "Security" },
  { id: 115, text: "Cybersecurity and ethical hacking.", category: "Security" },
  { id: 116, text: "Firefighting and rescue services.", category: "Security" },
  { id: 117, text: "Intelligence agencies and spying.", category: "Security" },
  { id: 118, text: "Border security and immigration.", category: "Security" },
  { id: 119, text: "Bodyguard and private security.", category: "Security" },
  { id: 120, text: "Coast guard and ocean rescue.", category: "Security" },
  // Media & Communication
  { id: 121, text: "Editing video and media content.", category: "Communication" },
  { id: 122, text: "Hosting TV or digital shows.", category: "Communication" },
  { id: 123, text: "Managing social media platforms.", category: "Communication" },
  { id: 124, text: "Copywriting for advertisements.", category: "Communication" },
  { id: 125, text: "Broadcast journalism and news.", category: "Communication" },
  { id: 126, text: "Professional blogging and vlogging.", category: "Communication" },
  { id: 127, text: "Corporate communication and PR.", category: "Communication" },
  { id: 128, text: "Translating and interpreting text.", category: "Communication" },
  { id: 129, text: "Publishing and book editing.", category: "Communication" },
  { id: 130, text: "Creative content strategy for brand.", category: "Communication" },
  // Agriculture & Sports
  { id: 131, text: "Professional sports and athletics.", category: "Sports" },
  { id: 132, text: "Agriculture and modern farming.", category: "Sports" },
  { id: 133, text: "Horticulture and plant breeding.", category: "Sports" },
  { id: 134, text: "Dairy and livestock management.", category: "Sports" },
  { id: 135, text: "Outdoor adventure and guiding.", category: "Sports" },
  { id: 136, text: "Physical training and gym coaching.", category: "Sports" },
  { id: 137, text: "E-sports and professional gaming.", category: "Sports" },
  { id: 138, text: "Sports management and events.", category: "Sports" },
  { id: 139, text: "Marine biology and aquaculture.", category: "Sports" },
  { id: 140, text: "Environment conservation and parks.", category: "Sports" },
];

export const PERSONALITY_QUESTIONS: Question[] = [
  // Extraversion vs Introversion
  { id: 141, text: "I feel energized after spending time with others.", category: "Extraversion" },
  { id: 142, text: "I often start conversations with strangers.", category: "Extraversion" },
  { id: 143, text: "I enjoy being the center of attention.", category: "Extraversion" },
  { id: 144, text: "I prefer to listen rather than speak in large groups.", category: "Extraversion" },
  { id: 145, text: "I need quiet time alone to recharge my energy.", category: "Extraversion" },
  { id: 146, text: "I am told I am a very social person.", category: "Extraversion" },
  { id: 147, text: "I like to attend large parties and events.", category: "Extraversion" },
  { id: 148, text: "I feel comfortable leading a group.", category: "Extraversion" },
  { id: 149, text: "I think carefully before I speak.", category: "Extraversion" },
  { id: 150, text: "Meeting new people excites me more than it scares me.", category: "Extraversion" },
  // Openness to Experience
  { id: 151, text: "I have a very active imagination.", category: "Openness" },
  { id: 152, text: "I enjoy thinking about abstract concepts.", category: "Openness" },
  { id: 153, text: "I like to try new and exotic foods.", category: "Openness" },
  { id: 154, text: "I am interested in art and philosophy.", category: "Openness" },
  { id: 155, text: "I prefer a fixed routine every day.", category: "Openness" },
  { id: 156, text: "I enjoy solving complex and creative puzzles.", category: "Openness" },
  { id: 157, text: "I often get lost in my own thoughts.", category: "Openness" },
  { id: 158, text: "I value originality more than tradition.", category: "Openness" },
  { id: 159, text: "I like to visit museums and galleries.", category: "Openness" },
  { id: 160, text: "I am always looking for better ways to do things.", category: "Openness" },
  // Conscientiousness
  { id: 161, text: "I pay attention to small details.", category: "Conscientiousness" },
  { id: 162, text: "I always finish my work on time.", category: "Conscientiousness" },
  { id: 163, text: "my workspace is always organized and clean.", category: "Conscientiousness" },
  { id: 164, text: "I am very careful and thorough in my work.", category: "Conscientiousness" },
  { id: 165, text: "I often procrastinate and leave things till the last minute.", category: "Conscientiousness" },
  { id: 166, text: "I prefer having things planned rather than spontaneous.", category: "Conscientiousness" },
  { id: 167, text: "I am a very disciplined person.", category: "Conscientiousness" },
  { id: 168, text: "I value accuracy over spped.", category: "Conscientiousness" },
  { id: 169, text: "I find it easy to stick to a schedule.", category: "Conscientiousness" },
  { id: 170, text: "I am reliable and people can depend on me.", category: "Conscientiousness" },
  // Agreeableness
  { id: 171, text: "I am sensitive to the feelings of others.", category: "Agreeableness" },
  { id: 172, text: "I try to avoid conflict whenever possible.", category: "Agreeableness" },
  { id: 173, text: "I enjoy helping others succeed.", category: "Agreeableness" },
  { id: 174, text: "I find it easy to trust people.", category: "Agreeableness" },
  { id: 175, text: "I am sometimes told I am too critical of others.", category: "Agreeableness" },
  { id: 176, text: "I am kind to everyone I meet.", category: "Agreeableness" },
  { id: 177, text: "I value harmony in a group setting.", category: "Agreeableness" },
  { id: 178, text: "I am a good mediator in arguments.", category: "Agreeableness" },
  { id: 179, text: "I feel bad when I have to deliver bad news.", category: "Agreeableness" },
  { id: 180, text: "I am cooperative rather than competitive.", category: "Agreeableness" },
  // Emotional Stability (Neuroticism)
  { id: 181, text: "I handle stress very well.", category: "Stability" },
  { id: 182, text: "I rarely get irritated or angry.", category: "Stability" },
  { id: 183, text: "I am calm even in high-pressure situations.", category: "Stability" },
  { id: 184, text: "I often worry about things that might go wrong.", category: "Stability" },
  { id: 185, text: "My mood can change very quickly.", category: "Stability" },
  { id: 186, text: "I am confident in my own abilities.", category: "Stability" },
  { id: 187, text: "I feel anxious when facing uncertainty.", category: "Stability" },
  { id: 188, text: "I am generally an optimistic person.", category: "Stability" },
  { id: 189, text: "I can bounce back quickly from failures.", category: "Stability" },
  { id: 190, text: "I feel overwhelmed by my responsibilities.", category: "Stability" },
  // Adaptability/Decision Making
  { id: 191, text: "I make decisions based on logic rather than emotion.", category: "Process" },
  { id: 192, text: "I am comfortable with sudden changes in plan.", category: "Process" },
  { id: 193, text: "I prefer working in a structured environment.", category: "Process" },
  { id: 194, text: "I enjoy taking calculated risks.", category: "Process" },
  { id: 195, text: "I am good at prioritizing multiple tasks.", category: "Process" },
  { id: 196, text: "I prefer working under minimal supervision.", category: "Process" },
  { id: 197, text: "I value career growth more than job security.", category: "Process" },
  { id: 198, text: "I am comfortable working in a fast-paced environment.", category: "Process" },
  { id: 199, text: "I prefer clear and direct communication.", category: "Process" },
  { id: 200, text: "I am motivated by deadlines and milestones.", category: "Process" },
];
